networks:
  hipy-network:
    name: hipy-network
    driver: bridge
    ipam:
      driver: default
      config:
        - gateway: 172.23.0.1
          subnet: 172.23.0.0/24
    driver_opts:
      com.docker.network.bridge.name: hipy-network

services:
  redis:
    container_name: hipy-redis
    restart: always
    image: redis:latest
    command: redis-server --requirepass hipy
    volumes:
       - /hipy/redis_data/:/data/
    ports:
      - "6379:6379"
    expose:
      - 6379
    networks:
      hipy-network:
        ipv4_address: 172.23.0.5
  postgres:
    container_name: hipy-pg
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_USER=hipy
      - POSTGRES_PASSWORD=hipy
      - POSTGRES_DB=hipy
    volumes:
      - /hipy/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      hipy-network:
        ipv4_address: 172.23.0.4
    command: [postgres, -c, max_connections=200]
  fastapi:
    container_name: hipy-fastapi
    image: hipy-server:20240106
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - "5707:5707"
    expose:
      - 5707
    networks:
      hipy-network:
        ipv4_address: 172.23.0.3
  vue:
    container_name: hipy-vue
    image: hipy-vue:4.3.0
    restart: always
    depends_on:
      - fastapi
    ports:
      - "80:80"
    expose:
      - 80
    networks:
      hipy-network:
        ipv4_address: 172.23.0.2