name: Sync Repositories

on:
  workflow_dispatch:
  schedule:
    # 定时任务，设定为每天运行一次，UTC时间00:00运行
    - cron: '0 0 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v3
      
    - name: Read repositories.txt
      id: read-repos
      run: |
        while read line; do
          # 获取 URL 和分支，默认为空表示没有指定分支
          url=$(echo $line | awk '{print $1}')
          branch=$(echo $line | awk '{print $2}')

          # 如果没有指定分支，则默认使用 main 分支
          if [ -z "$branch" ]; then
            branch="main"
          fi

          # 生成唯一的文件夹名称，使用主机名、路径和分支名来构造
          repo_name=$(echo $url | sed 's/https:\/\///' | sed 's/\//_/g')_$branch

          # 如果文件夹已经存在，先删除它
          if [ -d "$repo_name" ]; then
            echo "Removing existing directory $repo_name..."
            rm -rf $repo_name
          fi

          # 克隆仓库并删除 .git 文件夹
          echo "Cloning repository $repo_name from branch $branch..."
          git clone --depth 1 -b $branch $url $repo_name || echo "Failed to clone $url"
          rm -rf $repo_name/.git
        done < .github/repositories.txt

    - uses: stefanzweifel/git-auto-commit-action@v5
